const login = require("./login");
const authorize = require('./authorize');
const sensitive = require('./sensitive');
const dataLib = require('./dataLib');
const authRole = require('./authRole');
const authMenu = require('./authMenu');
const authority = require('./authority');
const customer = require('./customer');
const systemconfig = require('./systemconfig');
const package = require('./package');
const status = require('./status');
const serviceSetting = require('./serviceSetting');
const job = require('./job');
const identity = require('./identity');
const antiCheat = require('./antiCheat');
const appConfig = require('./appConfig');
const sysMessage = require('./sysMessage');
const sysVersion = require('./sysVersion');
const company = require('./company');
const wxPublicAccount = require('./wxPublicAccount');
const userManage = require("./userManage");
const seats = require('./seats');
const orderManagement = require("./orderManagement");
const transactionOrder = require("./transactionOrder");
const buyOrder = require("./buyOrder");
module.exports = function (app) {
    app.use("/api/manage", login);
    app.use(authorize);
    app.use('/api/sensitive', sensitive);
    app.use('/api/tconfig', dataLib);
    app.use('/api/auth', authRole);
    app.use('/api/auth', authMenu);
    app.use('/api/auth', authority);
    app.use('/api/customer', customer);
    app.use('/api/tSysCfg', systemconfig);
    app.use('/api/tPackage', package);
    app.use('/api/tStatus', status);
    app.use('/api/tService', serviceSetting);
    app.use('/api/tJob', job);
    app.use('/api/tconfig', identity);
    app.use('/api/tCheatConfig', antiCheat);
    app.use('/api/tAppConfig', appConfig);
    app.use('/api/tSystemMessage', sysMessage);
    app.use('/api/verCfg', sysVersion);
    app.use('/api/corp', company);
    app.use('/api/wxPublicAccount', wxPublicAccount);
    app.use("/api/user/", userManage);
    app.use('/api/seat', seats);
    app.use("/api/orderService", orderManagement);
    app.use("/api/uPayOrder", transactionOrder); 
    app.use("/api/buyorder", buyOrder); 
};