const config = require('../config/dev.env')
const api = config.MANAGE_BASE_API;
module.exports = {
    LOGIN: api + '/user/loginNormal',
    REGISTER: api + '/user/registerUser',
    LOGOUT: api + '/user/logout',
    GET_SESSION: api + '/user/getSession',
    //敏感词接口
    getWordList: api + '/sensitive/getWordList',
    getWordInfo: api + '/sensitive/getWordInfo',
    delWordUsage: api + '/sensitive/delWordUsage',
    addWordUsage: api + '/sensitive/addWordUsage',
    deleteWord: api + '/sensitive/deleteWord',
    addWord: api + '/sensitive/addWord',
    updateWordUsage: api + '/sensitive/updateWordUsage',
    //菜单
    getAuthMenuItemByMenuId: api + '/auth/getAuthMenuItemByMenuId',
    saveOrUpdateAuthMenuItem: api + '/auth/saveOrUpdateAuthMenuItem',
    deletAuthMenu: api + '/auth/deletAuthMenu',
    queryAuthMenuTreeBySubSystemAndBusiType: api + '/auth/queryAuthMenuTreeBySubSystemAndBusiType',
    saveOrUpdateAuthMenu: api + '/auth/saveOrUpdateAuthMenu',
    deleteAuthMenuItem: api + '/auth/deleteAuthMenuItem',
    saveMenuAuthItem: api + '/auth/saveMenuAuthItem',
    saveAuthMenuItem: api + '/auth/saveAuthMenuItem',
    //角色
    getAuthRoleItemByRoleId: api + '/auth/getAuthRoleItemByRoleId',
    saveOrUpdateAuthRoleItem: api + '/auth/saveOrUpdateAuthRoleItem',
    deleteAuthRole: api + '/auth/deleteAuthRole',
    queryAuthRole: api + '/auth/queryAuthRole',
    saveOrUpdateAuthRole: api + '/auth/saveOrUpdateAuthRole',
    queryAuthRoleByBusiType: api + '/auth/queryAuthRoleByBusiType',
    deleteAuthRoleByList: api + '/auth/deleteAuthRoleByList',
    updateAuthRoleStatusByList: api + '/auth/updateAuthRoleStatusByList',
    //权限
    deleteAuthItem: api + '/auth/deleteAuthItem',
    queryAuthItem: api + '/auth/queryAuthItem',
    saveOrUpdateAuthItem: api + '/auth/saveOrUpdateAuthItem',
    deleteAuthItemList: api + '/auth/deleteAuthItemList',
    //数据字典
    deleteTItemValue: api + '/tconfig/deleteTItemValue',
    updateTItemValue: api + '/tconfig/updateTItemValue',
    queryTItemValue: api + '/tconfig/queryTItemValue',
    addTItemValue: api + '/tconfig/addTItemValue',
    queryTItemValueByPager: api + '/tconfig/queryTItemValueByPager',

    updateTItemDefine: api + '/tconfig/updateTItemDefine',
    addTItemDefine: api + '/tconfig/addTItemDefine',
    deleteTItemDefine: api + '/tconfig/deleteTItemDefine',
    queryTItemDefine: api + '/tconfig/queryTItemDefine',
    queryTItemDefineByPager: api + '/tconfig/queryTItemDefineByPager',
    //客户
    deleteCustomer: api + '/customer/deleteCustomer',
    updateCustomerStatus: api + '/customer/updateCustomerStatus',
    updateCustomerRemarkr: api + '/customer/updateCustomerRemarkr',
    selectCustomerInfo: api + '/customer/selectCustomerInfo',
    getCustomerListByPage: api + '/customer/getCustomerListByPage',
    saveCustomer: api + '/customer/saveCustomer',
    //系统配置、系统变量
    delSysCfg: api + '/tSysCfg/delSysCfg',
    getSysCfg: api + '/tSysCfg/getSysCfg',
    getSysCfgListPaging: api + '/tSysCfg/getSysCfgListPaging',
    updateSysCfg: api + '/tSysCfg/updateSysCfg',
    addSysCfg: api + '/tSysCfg/addSysCfg',
    // 套餐
    deleteTPackageRoleById: api + '/tPackage/deleteTPackageRoleById',
    getTPackageRoleById: api + '/tPackage/getTPackageRoleById',
    addTPackageRole: api + '/tPackage/addTPackageRole',
    deleteTPackageById: api + '/tPackage/deleteTPackageById',
    getTPackageById: api + '/tPackage/getTPackageById',
    getTPackageListByPage: api + '/tPackage/getTPackageListByPage',
    addOrUpdateTPackage: api + '/tPackage/addOrUpdateTPackage',
    updateTPackageStatusById: api + '/tPackage/updateTPackageStatusById',
    // 状态配置
    getTStatusListByPage: api + '/tStatus/getTStatusListByPage',
    getTStatusTableById: api + '/tStatus/getTStatusTableById',
    delTStatusTableById: api + '/tStatus/delTStatusTableById',
    saveTStatusTable: api + '/tStatus/saveTStatusTable',
    delTStatusById: api + '/tStatus/delTStatusById',
    getTStatusById: api + '/tStatus/getTStatusById',
    saveOrUpdateTStatus: api + '/tStatus/saveOrUpdateTStatus',
    // 服务配置
    delTService: api + '/tService/delTService',
    getTServiceById: api + '/tService/getTServiceById',
    getTServiceListByPage: api + '/tService/getTServiceListByPage',
    saveOrUpdateTService: api + '/tService/saveOrUpdateTService',
    // tJob
    deleteTJobCfg: api + '/tJob/deleteTJobCfg',
    queryTJobCfg: api + '/tJob/queryTJobCfg',
    addTJobCfg: api + '/tJob/addTJobCfg',
    updateTJobCfg: api + '/tJob/updateTJobCfg',
    queryTJobCfgByPager: api + '/tJob/queryTJobCfgByPager',
    // 用户身份定义
    addTIdentity: api + '/tconfig/addTIdentity',
    deleteTIdentity: api + '/tconfig/deleteTIdentity',
    queryTIdentity: api + '/tconfig/queryTIdentity',
    addTIdentityService: api + '/tconfig/addTIdentityService',
    updateTIdentity: api + '/tconfig/updateTIdentity',
    deleteTIdentityService: api + '/tconfig/deleteTIdentityService',
    queryIdentityByPager: api + '/tconfig/queryIdentityByPager',
    queryTIdentityService: api + '/tconfig/queryTIdentityService',
    // 防作弊刷票配置
    queryAntiCheatCfgByPager: api + '/tCheatConfig/queryAntiCheatCfgByPager',
    modAntiCheatCfg: api + '/tCheatConfig/modAntiCheatCfg',
    delAntiCheatCfg: api + '/tCheatConfig/delAntiCheatCfg',
    queryAntiCheatCfg: api + '/tCheatConfig/queryAntiCheatCfg',
    addAntiCheatCfg: api + '/tCheatConfig/addAntiCheatCfg',
    // APP应用注册表
    updateAppConfig: api + '/tAppConfig/updateAppConfig',
    queryTAppConfigByPager: api + '/tAppConfig/queryTAppConfigByPager',
    queryAppConfig: api + '/tAppConfig/queryAppConfig',
    deleteAppConfig: api + '/tAppConfig/deleteAppConfig',
    addAppConfig: api + '/tAppConfig/addAppConfig',
    // 系统消息
    getTSystemMessageListByPage: api + '/tSystemMessage/getTSystemMessageListByPage',
    saveOrUpdateTSystemMessage: api + '/tSystemMessage/saveOrUpdateTSystemMessage',
    getTSystemMessageById: api + '/tSystemMessage/getTSystemMessageById',
    delTSystemMessage: api + '/tSystemMessage/delTSystemMessage',
    // 系统消息
    getIsNewVersion: api + '/verCfg/getIsNewVersion',
    deleteVersion: api + '/verCfg/deleteVersion',
    updateVersion: api + '/verCfg/updateVersion',
    addVersion: api + '/verCfg/addVersion',
    queryTAppVersionByPager: api + '/verCfg/queryTAppVersionByPager',
    // company management
    getCorpListMultiByPager: api + '/corp/getCorpListMultiByPager',
    getCorpInfoMulti: api + '/corp/getCorpInfoMulti',
    updateCorpStatusByCorpId: api + '/corp/updateCorpStatusByCorpId',
    updateCorpPackName: api + '/corp/updateCorpPackName',
    // 公众号
    getPublicAccountListByPage: api + '/wxPublicAccount/getPublicAccountListByPage',
    updatePublicAccountToActive: api + '/wxPublicAccount/updatePublicAccountToActive',
    updatePublicAccountListToDisabled: api + '/wxPublicAccount/updatePublicAccountListToDisabled',
    updatePublicAccountToBlockUp: api + '/wxPublicAccount/updatePublicAccountToBlockUp',
    updatePublicAccountToUnAuthorization: api + '/wxPublicAccount/updatePublicAccountToUnAuthorization',
    updatePublicAccountListStatusToDelete: api + '/wxPublicAccount/updatePublicAccountListStatusToDelete',
}